#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Removes a finalizer from a resource if its stuck in terminating because of it"
    echo
    echo "Usage:     kubectl removefinalizer <kind> <name>"
    echo "Example:   kubectl removefinalizer pod foo"
    echo
    exit 1
fi

exec kubectl patch $@ --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]'
